### PR TITLE
slang: Fixing for upstream changes.

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by piotr-binkowski** [comment]
I'm not sure if we should disable the static build patch because we are still using GCC8 from the system to build Slang. I've prepared an updated patch that enables static build on upstream Slang
[static-build.patch](https://github.com/SymbiFlow/conda-packages/files/4128141/static-build.txt)

**Comment by mithro** [comment]
Oh, I thought https://github.com/SymbiFlow/conda-packages/issues/64#issuecomment-579565376 was implying that static compilation was upstream now.

**Comment by mithro** [comment]
@piotr-binkowski Feel free to take over this change.

**Comment by piotr-binkowski** [comment]
In the end this was fixed in #67

**Pull request closed without merging**
