### PR TITLE
surelog: move dependencies to build section

### LINKED ISSUE #105: Surelog fails to build becuase cmake is confused about Python version
https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/349642231#L3447

[Installs Python (gets 3.7.6)](https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/349642231#L3582), later in cmake it has trouble finding it. In fact is claims it finds it, but then also not...

This might be an issue with conflicting Python versions on the build system ? Is there something that needs to be done to have cmake be more robust, or does the CI environment be changed ?

```
CMake Error at /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
3777  Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) (found
3778  suitable version "3.7", minimum required is "3.3")
3779Call Stack (most recent call first):
3780  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
3781  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPython/Support.cmake:2398 (find_package_handle_standard_args)
3782  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPython3.cmake:311 (include)
3783  CMakeLists.txt:45 (find_package)
```

### PR DESCRIPTION
**Pull request by tgorochowik**
An attempt to fix #105

### CODE REVIEW

**Comment by tgorochowik** [comment]
I didn't notice #106. Closing.

**Comment by hzeller** [comment]
Though also #106 is not working yet. Now it hangs on libuuid; do you have an idea ?

**Comment by tgorochowik** [comment]
@hzeller unfortunately I don't see anything obvious, however since the build works just fine for the uhdm-integration package I think we could just copy the build commands from there - is there a reason why we shouldn't?

**Comment by tgorochowik** [comment]
@hzeller please share your thoughts. The surelog build here is successful.

**Comment by tgorochowik** [comment]
Just to clarify - I just copied most of the stuff from the uhdm-integration packages so some of the changes may not really be needed (like the flex requirement).

**Review by hzeller — APPROVED** [review]
Lhis looks great, Surelog compiles!.
Let's merge it.

**Pull request merged**
