### PR TITLE
Re-enable tcmalloc again.

### PR DESCRIPTION
**Pull request by hzeller**
Compilation with tcmalloc stopped working before. This pull request is on its quest to find out how to get it going again.

### CODE REVIEW

**Comment by hzeller** [comment]
Q: @mithro is there a simple way to run the conda build locally to figure out why the linker 
[fails to find tcmalloc](https://travis-ci.com/SymbiFlow/conda-packages/jobs/290634608#L2573) even though [gperftools are installed](https://github.com/SymbiFlow/conda-packages/blob/master/surelog/meta.yaml#L26) ? In particular it worked till recently, possibly until the introduction to UHDM libs were linked, so I suspect there might be some `-L` mumbling needed for this to work; but since I don't want to wait 30min for each experiment, a local test would be great.

**Comment by mithro** [comment]
`./conda-env.sh build XXXX`

**Comment by hzeller** [comment]
Thanks, that helped to reproduce it locally.

Created https://github.com/alainmarcel/Surelog/pull/194 to hopefully better auto-find the correct location.

**Comment by hzeller** [comment]
Ready to merge; this change plus the already committed https://github.com/alainmarcel/Surelog/pull/194 make the linking with tcmalloc work.

**Pull request merged**
