### PR TITLE
Attempt to add threading support to VPR.

### LINKED ISSUE #14: VPR being compiled without thread support
Just noticed the following warning on the kokoro CI:
```
Warning 1: VPR was compiled without parallel execution support, ignoring the specified number of workers (1)
```

This might explain the excessive run times.  Should be pretty straight forward to fix, just need to have the expected thread library installed during packaging.

### PR DESCRIPTION
**Pull request by litghost**
Fixes #14

### CODE REVIEW

**Comment by litghost** [comment]
Test build looks good:
```
..
-- Found TBB: /usr/include (found version "4.2")  
```

**Comment by mithro** [comment]
Shouldn't it actually be finding `tbb` in the conda repository, not at `/usr/include`?

**Comment by litghost** [comment]
> Shouldn't it actually be finding `tbb` in the conda repository, not at `/usr/include`?

Ya, it should be, and is in the latest attempt:


```
-- Found TBB: $PREFIX/include (found version "2019.0")  
-- Tatum: will support parallel execution using 'tbb'
```

**Comment by mithro** [comment]
@litghost This is failing when linking abc. I'm pretty sure it is because you are running out of memory. Pretty sure I saw this with Yosys too. I'm testing by doing a build with the following extra patch -> https://github.com/mithro/conda-hdmi2usb-packages/commit/db8e39ab5155e3d0257f28179617839b5bbbb3ed

**Comment by mithro** [comment]
Currently still building but;
 * [Before](https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520518047)
 * [After](https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520519865)

**Comment by litghost** [comment]
> @litghost This is failing when linking abc. I'm pretty sure it is because you are running out of memory. Pretty sure I saw this with Yosys too. I'm testing by doing a build with the following extra patch -> [mithro@db8e39a](https://github.com/mithro/conda-hdmi2usb-packages/commit/db8e39ab5155e3d0257f28179617839b5bbbb3ed)

I buy that, Travis's memory limit is quiet annoying.

**Comment by litghost** [comment]
VTR enabled LTO, probably worth trying to disable it for now.  I believe that threading support >>> LTO.

**Comment by mithro** [comment]
My second build seems to be the failing with the following;
```
cd $SRC_DIR/build && $PREFIX/bin/cmake -E cmake_depends "Unix Makefiles" $SRC_DIR $SRC_DIR/libs/EXTERNAL/libsdcparse $SRC_DIR/build $SRC_DIR/build/libs/EXTERNAL/libsdcparse $SRC_DIR/build/libs/EXTERNAL/libsdcparse/CMakeFiles/sdcparse_test.dir/DependInfo.cmake --color=
/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/vtr_1555370028822/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /usr/lib/libtbb.so: undefined reference to `memcpy@GLIBC_2.14'
```

It shouldn't be linking against `libttb.so`?

**Comment by litghost** [comment]
> My second build seems to be the failing with the following;
> 
> ```
> cd $SRC_DIR/build && $PREFIX/bin/cmake -E cmake_depends "Unix Makefiles" $SRC_DIR $SRC_DIR/libs/EXTERNAL/libsdcparse $SRC_DIR/build $SRC_DIR/build/libs/EXTERNAL/libsdcparse $SRC_DIR/build/libs/EXTERNAL/libsdcparse/CMakeFiles/sdcparse_test.dir/DependInfo.cmake --color=
> /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/vtr_1555370028822/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /usr/lib/libtbb.so: undefined reference to `memcpy@GLIBC_2.14'
> ```
> It shouldn't be linking against `libttb.so`?

Looks like it is using the wrong libttb.so, maybe undo what I did to add it to the host here: https://github.com/SymbiFlow/conda-packages/pull/15/files#diff-354f30a63fb0907d4ad57269548329e3R28

I added libtbb-devel to the conda metadata, that should be enough.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/SymbiFlow/conda-packages/pull/15">Attempt to add threading support to VPR. by litghost · Pull Request #15 · SymbiFlow/conda-packages</a></strong></div><div>Fixes #14</div></blockquote>

**Comment by mithro** [comment]
Next build running here -> https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926

<blockquote><div><strong><a href="https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by litghost** [comment]
> Next build running here -> https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926
> 
> > **[Travis CI - Test and Deploy Your Code with Confidence](https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926)**

That worked, what did you change?

<blockquote><div><strong><a href="https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by mithro** [comment]
I don't quite understand why that one worked?

**Comment by mithro** [comment]
Another build running here -> https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926

<blockquote><div><strong><a href="https://travis-ci.org/mithro/conda-hdmi2usb-packages/jobs/520531926">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by mithro** [comment]
That build also passed...

**Comment by mithro** [comment]
Well VtR is working;

Job | ENV | State
-- | -- | --
239.1 | \["PACKAGE=vtr CONDA\_CHANNELS=conda-forge"\] | passed
239.2 | \["PACKAGE=yosys"\] | passed
239.3 | \["PACKAGE=openocd"\] | errored
239.4 | \["PACKAGE=riscv32\/binutils"\] | passed
239.5 | \["PACKAGE=arachne-pnr"\] | failed
239.6 | \["PACKAGE=icestorm"\] | passed
239.7 | \["PACKAGE=iverilog"\] | failed

**Pull request merged**
