### PR TITLE
Add sv-parser package

### PR DESCRIPTION
**Pull request by dalance**
I want to add sv-parser package for sv-tests.

### CODE REVIEW

**Comment by mithro** [comment]
> ValueError: License file given in about/license_file (/home/travis/build/SymbiFlow/conda-packages/sv-parser/LICENSE-MIT LICENSE-APACHE) does not exist in source root dir or in recipe root dir (with meta.yaml)


```
Packaging sv-parser
INFO:conda_build.build:Packaging sv-parser
INFO conda_build.build:build(1566): Packaging sv-parser
Packaging sv-parser-33eff2dd93fd74799e3e06453235fa2c800c40cd-20191023_074245
INFO:conda_build.build:Packaging sv-parser-33eff2dd93fd74799e3e06453235fa2c800c40cd-20191023_074245
INFO conda_build.build:bundle_conda(886): Packaging sv-parser-33eff2dd93fd74799e3e06453235fa2c800c40cd-20191023_074245
number of files: 1
WARNING (sv-parser,bin/parse_sv): did not find - or even know where to look for: /lib64/ld-linux-x86-64.so.2
WARNING (sv-parser,bin/parse_sv): did not find - or even know where to look for: $RPATH/libdl.so.2
WARNING (sv-parser,bin/parse_sv): did not find - or even know where to look for: $RPATH/libc.so.6
WARNING (sv-parser,bin/parse_sv): did not find - or even know where to look for: $RPATH/librt.so.1
WARNING (sv-parser,bin/parse_sv): did not find - or even know where to look for: $RPATH/libpthread.so.0
WARNING (sv-parser,bin/parse_sv): did not find - or even know where to look for: $RPATH/libgcc_s.so.1
Fixing permissions
Traceback (most recent call last):
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 449, in main
    execute(sys.argv[1:])
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 440, in execute
    verify=args.verify, variants=args.variants)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 2339, in build_tree
    notest=notest,
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 1638, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 1010, in bundle_conda
    output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 704, in create_info_files
    copy_license(m)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 398, in copy_license
    "source root dir or in recipe root dir (with meta.yaml)".format(src_file))
ValueError: License file given in about/license_file (/home/travis/build/SymbiFlow/conda-packages/sv-parser/LICENSE-MIT LICENSE-APACHE) does not exist in source root dir or in recipe root dir (with meta.yaml)
```

**Comment by dalance** [comment]
Thanks. I fixed it.

**Comment by mithro** [comment]
```
bin/parse_sv
info/about.json
info/files
info/git
info/hash_input.json
info/index.json
info/licenses/LICENSE-MIT
info/paths.json
info/recipe/build.sh
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
info/recipe/meta.yaml.template
info/recipe/recipe_append.yaml
info/test/run_test.sh
```

**Comment by mithro** [comment]
Looks good as far as I can tell....

**Pull request merged**
