### PR TITLE
Remove use of conda-forge from capnproto-java.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by litghost** [comment]
@mithro / @PiotrZierhoffer I've switched to bionic because the linker in xeniel encountered a bug.  There are likely other solutions if moving to bionic is not acceptable.

**Comment by mithro** [comment]
@litghost - This likely means the conda package is using the wrong compiler (IE Not the one provided by conda?)

**Comment by litghost** [comment]
> @litghost - This likely means the conda package is using the wrong compiler (IE Not the one provided by conda?)

Ya

**Comment by litghost** [comment]
This is ready for review.

**Comment by litghost** [comment]
@PiotrZierhoffer / @mithro This PR still needs a review

**Review by PiotrZierhoffer — APPROVED** [review]
lgtm

**Pull request merged**
