### PR TITLE
Attempt to fix Surelog build: we need python development files.

### LINKED ISSUE #105: Surelog fails to build becuase cmake is confused about Python version
https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/349642231#L3447

[Installs Python (gets 3.7.6)](https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/349642231#L3582), later in cmake it has trouble finding it. In fact is claims it finds it, but then also not...

This might be an issue with conflicting Python versions on the build system ? Is there something that needs to be done to have cmake be more robust, or does the CI environment be changed ?

```
CMake Error at /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
3777  Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) (found
3778  suitable version "3.7", minimum required is "3.3")
3779Call Stack (most recent call first):
3780  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
3781  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPython/Support.cmake:2398 (find_package_handle_standard_args)
3782  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/surelog_1592301850162/_build_env/share/cmake-3.17/Modules/FindPython3.cmake:311 (include)
3783  CMakeLists.txt:45 (find_package)
```

### PR DESCRIPTION
**Pull request by hzeller**
Fixes #105

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Let's see if this works.

**Comment by hzeller** [comment]
(not merge yet, work in progress)

**Comment by hzeller** [comment]
So, `python-dev` is not the right package: https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/352794276#L1297

How do I get Python development files (Python.h and shared lib)?

Adding @mithro as he most likely knows all things Python related.

<blockquote><div><strong><a href="https://travis-ci.com/github/SymbiFlow/conda-packages/jobs/352794276#L1297">Travis CI - Test and Deploy with Confidence</a></strong></div><div>Travis CI enables your team to test and ship your apps with confidence. Easily sync your projects with Travis CI and you'll be testing your code in minutes.</div></blockquote>

**Comment by hzeller** [comment]
Anyone of you knows what the right conda package is to get Python development files ? Searching on Anaconda did not enlighten me much ...

**Comment by mithro** [comment]
@hzeller They are in the "python" package -- the issue is cmake not finding them properly.

**Comment by hzeller** [comment]
Cmake finds the `Interpreter`, but not the `Development` files.

I have seen something like that on some workstation where the python interpreter it finds is a different version than development files that might be on the system (available was 3.7 with interpreter and development, and 3.8 with only interpreter); unfortunately the cmake rule does not do an exhaustive search of versions where it has one _and_ the other. On a workstation, I can fix that by uninstalling a stray version of Python (in that case above, if 3.8 is removed, it found Interpreter+Development).

I suspect something like this is going on in this conda-build, so that possibly the `python` install provides a new version of the interpreter, but not the new version of development files. Or maybe it provides both, but cmake finds the 'other' version of Python on the build machine.

**Comment by PiotrZierhoffer** [comment]
@hzeller In prjtrellis package we have the following (https://github.com/litex-hub/litex-conda-eda/blob/master/bit/prjtrellis/build.sh#L23)

```
	-DPYTHON_EXECUTABLE=$(which python) \
	-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
	-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \
```

If you can run the interpreter before running cmake, maybe this is the easiest way to approach it?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/litex-hub/litex-conda-eda">litex-hub/litex-conda-eda</a></strong></div><div>Conda recipes for FPGA EDA tools for simulation, synthesis, place and route and bitstream generation. - litex-hub/litex-conda-eda</div></blockquote>

**Comment by PiotrZierhoffer** [comment]
Using these variables is also mentioned here: https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html

<blockquote><div><strong><a href="https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html">FindPythonLibs — CMake 3.0.2 Documentation</a></strong></div></blockquote>

**Review by tgorochowik — COMMENTED** [review]
I think that what you did in #106 (moving the python requirement to the `build` section) was the proper fix for the python issue.

I think that the issue with `libuuid` in #106 is a separate problem

**Comment by PiotrZierhoffer** [comment]
Agreed. I thought this problem is there *despite* having python in the `build` section.

**Comment by tgorochowik** [comment]
@hzeller I reopened #107 in which besides moving the python requirement I modified the build instructions to mimic what we do for the uhdm-integration packages (for which the surelog build works).

**Comment by hzeller** [comment]
Closing. #107 is the right one.

**Pull request closed without merging**
