### PR TITLE
prjxray-db: add conda package

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by acomodi** [comment]
@mithro FYI. I have a question though. Is there a way to have the data files of a conda package in the root directory of the conda environment when the conda package gets installed?
This because, for instance, an env variable would need to be created with the DB location for FPGA tool perf purposes.

**Comment by mithro** [comment]
> @mithro FYI. I have a question though. Is there a way to have the data files of a conda package in the root directory of the conda environment when the conda package gets installed?
> This because, for instance, an env variable would need to be created with the DB location for FPGA tool perf purposes.

I don't quite get understand what you are asking? The DB files should be in the equivalent of `/usr/share/prjxray` type directory.

**Comment by acomodi** [comment]
@mithro Yeah, I actually figured that out.
For instance, I had problems with nextpnr-xilinx data files that were in the `share/nextpnr-xilinx/` path of the conda package, but upon the conda nextpnr-xilinx installation, those files did not end up in the `CONDA_DIR/share/nextpnr-xilinx/` path. Apparently I had some issues in the conda environment on my local machine.

Currently the database should get copied in the `CONDA_DIR/share/symbiflow/prjxray-db/` path

**Comment by acomodi** [comment]
@mithro PTAL

**Comment by acomodi** [comment]
@mithro ping

**Comment by mithro** [comment]
This needs a rebase.

**Comment by acomodi** [comment]
> This needs a rebase.

@mithro Done

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by mithro** [comment]
Merge if green.

**Comment by PiotrZierhoffer** [comment]
I believe this can be merged. The only two packages failing are icestorm (fixed on master) and surelog (not yet working, but not related)

**Pull request merged**
