### PR TITLE
slang: update for upstream changes

### LINKED ISSUE #64: Slang currently fails building
Here is an example run
https://travis-ci.com/SymbiFlow/conda-packages/jobs/275491438

### PR DESCRIPTION
**Pull request by piotr-binkowski**
Fixes #64

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by mithro** [comment]
Merge if green.

**Comment by MikePopoloski** [comment]
Bump on this

**Comment by kgugala** [comment]
seems like travis was stalled for 5 days o_O. I have restarted it. Let's wait for green CI

**Comment by piotr-binkowski** [comment]
Slang now builds correctly, Surelog still fails but that is not really related to those changes as it fails to build even on master

**Pull request merged**
