### PR TITLE
Add moore package

### PR DESCRIPTION
**Pull request by fabianschuiki**
Add the [moore] HDL compiler for use in the sv-tests suite.

[moore]: https://github.com/fabianschuiki/moore

### CODE REVIEW

**Comment by mithro** [comment]
@fabianschuiki Please ignore the cloud build trigger, that was something I was experimenting with.

**Comment by mithro** [comment]
A test build of the package will appear at https://travis-ci.com/SymbiFlow/conda-packages/jobs/247341594 in about ~1 hour...

<blockquote><div><strong><a href="https://travis-ci.com/SymbiFlow/conda-packages/jobs/247341594">Travis CI - Test and Deploy with Confidence</a></strong></div></blockquote>

**Comment by fabianschuiki** [comment]
I think I've missed something. Added WIP prefix until I find the issue and can fix it.

**Comment by fabianschuiki** [comment]
Finally managed to fix this. For some reason, building with the conda-provided rustc/cargo breaks. Now using `rustup.sh` for the time being until that can be sorted out.

Please feel free to merge once checks pass 👍

**Comment by fabianschuiki** [comment]
Moore build passes. The failing test is slang which already failed prior to this PR.

**Comment by mithro** [comment]
```
bin/moore
info/about.json
info/files
info/git
info/hash_input.json
info/index.json
info/licenses/LICENSE-MIT
info/paths.json
info/recipe/build.sh
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
info/recipe/meta.yaml.template
info/recipe/recipe_append.yaml
info/test/run_test.sh
```

**Comment by fabianschuiki** [comment]
Looks as intended. I'll now add the moore package as a dependency in [sv-tests #340](https://github.com/SymbiFlow/sv-tests/pull/340).

**Pull request merged**
