### PR TITLE
Add yosys-plugins package

### PR DESCRIPTION
**Pull request by tmichalak**
Once the XDC and FASM plugins for Yosys are ready we will have to create a conda pacakge with them. This PR currently just checks that the recipe works.

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by mithro** [comment]
You might want to check the plugin works.

**Comment by tmichalak** [comment]
@mithro I checked that the plugin works by building the package locally and installing it locally as well.
Without this merged the arch-defs PR will always fail Travis (https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1158)

**Review by mithro — APPROVED** [review]
LGTM!

**Pull request merged**
