### PR TITLE
Remove Yosys dependency on readline for more robustness.

### PR DESCRIPTION
**Pull request by hzeller**
Context:
https://github.com/SymbiFlow/sv-tests/pull/851
https://github.com/SymbiFlow/conda-packages/pull/110

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Looks like uhdm-integration does not use `$(MAKE)` when calling the yosys Makefile, losing the variable. Let me fix that first over there.

**Comment by hzeller** [comment]
Let's re-trigger once https://github.com/alainmarcel/uhdm-integration/pull/27 is pushed.

**Comment by hzeller** [comment]
Alright, this now successfully compiles without readline, reducing the target runtime dependencies.

**Review by tgorochowik — APPROVED** [review]
LGTM

**Pull request merged**
